### PR TITLE
Allow hardware information to be shown

### PR DESCRIPTION
**Pull request by mwarning**
Allow hardware information to be displayed (CPU, RAM, Flash), if it is present in the JSON data.

Rows are also hidden when there is no data.

### CODE REVIEW

**Comment by mwarning** [comment]
@aparcar is that something nice to have? Not that we use this feature now, but it might become useful in the future.

**Comment by aparcar** [comment]
Can you show a demo?

**Comment by mwarning** [comment]
https://mwarning.de/yafs/www/
Search for "1&1 HomeServer"

**Comment by mwarning** [comment]
But it might be nicer to show hardware data to the build data, not on top...

**Comment by aparcar** [comment]
Beside the design decision, I think this gets quite big the more data you add also becomes less easy merge-able with the OpenWrt `profiles.json` file. Don't you think it is better to have a second file containing such data?

**Comment by mwarning** [comment]
A second file might be good idea.

**Comment by mwarning** [comment]
Anyway, this feature is not something we need right now. But it is interesting to discuss this.

**Comment by aparcar** [comment]
Fine with me, although I did not see this in action yet. 

There are some additional hardware information which could be valuable, some time ago I created a mock up [here](https://aparcar.github.io/openwrt-devices/devices/tp-link_archer_c7_v5/)

The data is available as [YAML](https://github.com/aparcar/openwrt-devices/blob/master/_data/devices/adb_av4202n.yml), not JSON, but could be easily converted. If we'd stick to the YAML we could collaborate with the official OpenWrt wiki and have a community organized database.

A YAML parser for JavaScript exists [here](https://github.com/nodeca/js-yaml)

image

**Comment by mwarning** [comment]
This looks awesome. :-)

But it might be better to setup this in a different project. Both project scopes might be too divergent.

**Comment by mwarning** [comment]
The code is now easy to extend to allow this. But this is out of the scope of this project. Closing.

**Comment by aparcar** [comment]
Actually it could be interesting to load such information at some point. It's all available as YAML but could be easily converted to JSON https://github.com/aparcar/devices/blob/main/data/8devices_carambola.yaml

**Pull request closed without merging**
